### ISSUE TITLE
Activities (touring, local meetup etc) identified and agreed-on

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/Community-Gatherings#17]
- [x] Look into potential activities or tour time for volunteers + staff
- [ ] Identify whether we want other activities for just volunteers 

@francjp & @bacharakis

**Comment by francjp** [comment]
Hello,

I would suggest try to see if we can organize some city tour or something like that, since people will want to engage for sure. However, we need to check how much time we will have in the agenda to do this.

Related to the local meetup, we are in discussions with Emma about this, so once we have clarification on that side, I can update here. However, I'm not confident that we will have enough time to organize and execute the meetup while we are at All Hands.

Cheers,

**Comment by francjp** [comment]
Free tours for London:
http://www.newlondon-tours.com/
http://www.freetoursbyfoot.com/london-tours/

I'm checking more options with Valentin.

**Comment by ensowhat** [comment]
A walking tour with the volunteers is on planning for Tuesday, (it's the only evening where we'll all be available).

**Comment by ensowhat** [comment]
The initial idea is to do a walking tour from the hotel to Big Ben, visiting a bunch of cool locations on the way, and to go back to the hotel/a dinner location by Tube.

**Comment by bacharakis** [comment]
@ensowhat How much time we will have for the city tour?

**Comment by francjp** [comment]
@bacharakis in theory we have around 2 hours (3 depending on dinner plans).
Schedule says that days ends at 6 PM, and ideally we should arrange dinner for 8 - 8:30 PM.

We have a couple of ideas, but probably this will be the only activity that we can arrange for everyone.

Cheers,

**Comment by alex-mayorga** [comment]
¡Hola!

Hoping to wander the streets of London with my fellow Mozillian =)

¡Gracias!

**Comment by GapsoNtm** [comment]
Great idea :)

**Comment by ioana-chiorean** [comment]
This was a success from the pictures seen! ( the issue can be closed) 

![photo_2016-06-28_11-45-43](https://cloud.githubusercontent.com/assets/1391451/16409379/e551d8be-3d25-11e6-8c2c-8efae1d00869.jpg)
